### ISSUE TITLE
Breaking builds

### ISSUE THREAD

**Issue by johnhungerford** [clulab/conceptdiscovery#6]
Hi all! We have been trying to dockerize our concepts application so we can run it as a REST service within DART, but we've found that the concept-discovery dependency is breaking the assembly. When we run the jar output, it is unable to find our main class. We have verified that this is due to the concept-discovery dependency by building a simple hello world application, which builds fine, and then as soon as we add concept-discovery (even if we don't actually use the library) it breaks.

Since it is not published as a maven artifact, we are currently using it as follows:

```
lazy val conceptDiscoveryProject = RootProject( uri( s"${conceptDiscovery}#${conceptDiscoveryVersion}" ) )

lazy val root = ( project in file( "." ) )
  .dependsOn( conceptDiscoveryProject )
  .enablePlugins( JavaAppPackaging )
  .settings( ... )
```

where `conceptDiscovery` is the github repo and `conceptDiscoveryVersion` is the commit hash for the version we are using (currently [71d306ac7d0164e84153472617a59715f4b8e3d7](https://github.com/clulab/conceptdiscovery/commit/71d306ac7d0164e84153472617a59715f4b8e3d7), but we've had the same problem with all the commits we've tried).

Setting the `mainClass` setting in `build.sbt` has not made any difference (I've tried every which way...).

I suspect the issue has something to do with the fact that conceptDiscovery includes its own main class as well other dependencies with their own main classes. Any thoughts about this?

@kwalcock @MihaiSurdeanu

**Comment by MihaiSurdeanu** [comment]
This sounds like a job for @kwalcock :)

**Comment by johnhungerford** [comment]
Thanks @kwalcock. I'll try jitpack and see if that does anything. `mainClass` hasn't helped.

I have no idea what's causing the problem. All I know is that as soon as I add conceptDiscovery as a dependency the build breaks. (We've used RootProject to import unpublished github repos before and haven't had this problem.)

I just made a fork of conceptdiscovery and removed ` DiscoverAndRankConceptsApp` to see if that would make a difference and it didn't.

**Comment by kwalcock** [comment]
If jitpack doesn't help, I'll try to reproduce.  Thanks for being the first to attempt this.

**Comment by johnhungerford** [comment]
@kwalcock I was able to save the build by adding the following to our assembly merge strategy:

```
    case PathList( "META-INF",  xs @ _*) => MergeStrategy.discard

```

Hopefully this won't cause problems when I try to build a functioning application (right now it's still just hello world), but at least it's clear where the problem is.

**Comment by kwalcock** [comment]
Good find.  If the jars have conflicting files, the build can fail.  Here's what happened when we ran into that problem once: https://github.com/clulab/eidos/blob/master/assembly.sbt.

**Comment by johnhungerford** [comment]
Seems to be working now. Thanks for pointing me to your example -- I'll be copying that if things start to fail ;)
